​runtime​: ​nodejs16 
 ​env​: ​standard 
  
 ​handlers​: 
 ​  - ​url​: ​/.* 
 ​    ​script​: ​auto 
 ​    ​secure​: ​always 
  
 ​instance_class​: ​B1 
 ​basic_scaling​: 
 ​  ​max_instances​: ​1 
 ​  ​idle_timeout​: ​300s